version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sistema-financeiro-db-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sistema_financeiro
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sistema_financeiro"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
