services:
  # Apenas banco para desenvolvimento (app roda local)
  db:
    image: postgres:16-alpine
    container_name: sistema-financeiro-db-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sistema_financeiro
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sistema_financeiro"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

  # Opcional: Redis para cache (se precisar)
  redis:
    image: redis:7-alpine
    container_name: sistema-financeiro-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - dev-network
    profiles:
      - with-redis

volumes:
  postgres_dev_data:
    driver: local

networks:
  dev-network:
    driver: bridge
